### ISSUE TITLE
Inference compatibility with CPU

### ISSUE THREAD

**Issue by caviri** [irmlma/next-location-prediction#2]
Hello @hongyeehh, 

I'm testing this component on my M1 Pro. And I wanted to share some news: 

- Training: Let's not even attempt it. Docker is not compatible with Apple GPUs so it jumps into CPU and it would takes ages. 
- Inference: This can be a more realistic case of use. I run it in about 5-8 minutes however I needed to modify your code a bit. 

I needed to specify the device where to load the weights here:

https://github.com/irmlma/next-location-prediction/blob/33e17ae3f857b22a6164ecb5f9c384f62b279b34/example/run.py#L91

I modified it by: 

```
model.load_state_dict(torch.load(os.path.join(config.run_save_root, config.pretrain_dir, "checkpoint.pt"),map_location=device))
```

I need to still test it on my GPU but it should work too as device will be updated to `torch.device('cuda')`

What do you think?

**Comment by hongyeehh** [comment]
Hi @caviri, 

I should have made the code compatible with both CPUs and GPUs, but thanks a lot for testing! The modification looks good, and from my understanding, it should work. You can directly change the code. Let me know your testing results!

**Comment by caviri** [comment]
Great I created a PR (https://github.com/irmlma/next-location-prediction/pull/3) as I have no rights to modify your code.

**Comment by hongyeehh** [comment]
The PR is now merged. I have also granted you the rights to maintain.
