### ISSUE TITLE
Output folder naming

### ISSUE THREAD

**Issue by caviri** [irmlma/next-location-prediction#4]
Hello @hongyeehh, 

One thing we need in order to make the component compatible with any other components is the ability to define custom output names. 

When I run this tool I can see how the folder names goes as `original-dataset`_`network`_`date?`. 

```
dtepr_mhsa_1716103576/ 
dtepr_mhsa_1716108417
```

Would be possible to add a config field in which this folder name can be declare? Otherwise, is there any way to know which folder name is going to have an output?

**Comment by dirmeier** [comment]
Hey, maybe this is a good opportunity to discuss about unifying the interfaces of our methods to make it easier for you and potential users? Cheers, S

**Comment by caviri** [comment]
Sure, that would be really helpful. So far, right now the interface that we are using from the ODTP perspective is describe [here](https://github.com/odtp-org/odtp-next-location-prediction/blob/main/odtp.yml) in the `parameters` section. Those parameters can be declared as environment variables in the docker image and tool will be executed with them. We are still working on the `data-input`/`data-output` declaration. 

However, at this point for us would be enough to have the option to define the output folder naming in order to complete the first working version of the component.

**Comment by hongyeehh** [comment]
The latest commit fixed this issue with the config file's new `run_name` parameter. A folder with `run_name` will be created (if not existing) under `run_save_root`. 

By the way, I am not able to access the link @caviri; maybe the provided repo is private?

**Comment by caviri** [comment]
Hello @hongyeehh, thanks for the changes. I'll include them in the next version of the component. 

I forgot to make public the repository, now you should have access to it. I tested it in different platforms including ARM64, AMD64 (with and without Nvidia GPU).

**Comment by hongyeehh** [comment]
Thanks for the link! I'll close the issue as completed.
