### ISSUE TITLE
Citation.cff

### ISSUE THREAD

**Issue by caviri** [irmlma/next-location-prediction#5]
Hello, have you consider the use of a `Citation.cff`? This is an standard way to add attribution to a repository. By placing this file on the root of your repository, github will parse it and provide an easy way to copy and reuse the right reference to your software.

More information here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

Cheers,
Carlos

**Comment by hongyeehh** [comment]
Hey, thanks for the tip. A `cff` file with the reference information is pushed :)
